import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReduxProvider, LayoutProvider } from '@/providers/'
import Header from '@/components/Header';
import Content from '@/components/Content';
import Footer from '@/components/Footer';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <LayoutProvider>
            <div id="main-content" className="d-flex flex-column min-vh-100">
              <Header />
                <Content>
                  {children}
                </Content>
              <Footer />
            </div>
          </LayoutProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
