FROM node:20 AS builder

WORKDIR /app

COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install

COPY ./frontend .
RUN npm run build   # Gera a pasta .next

# --- Produção ---
FROM node:20

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000
CMD ["npm", "start"]
