services:
  app:
    build: .
    container_name: laravel-next-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
