name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências do frontend
        run: |
          cd frontend
          npm ci

      - name: Rodar testes do frontend
        run: |
          cd frontend
          npm test -- --ci --passWithNoTests

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy no servidor
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} "
            cd ~/CooperDash && \
            git pull origin main && \
            docker-compose -f docker-compose.prod.yml down && \
            docker-compose -f docker-compose.prod.yml build && \
            docker-compose -f docker-compose.prod.yml up -d && \
            docker system prune -af --volumes
          "
