name: Semantic Release
on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install root dependencies
        run: |
          # Desabilitar Husky durante a instalação
          npm ci --ignore-scripts
          # Instalar apenas semantic release e dependências necessárias
          npm install --no-save semantic-release @semantic-release/git @semantic-release/changelog

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci --ignore-scripts

      - name: Run Semantic Release (skip husky)
        run: |
          # Desabilitar Husky para o semantic release
          git config --global core.hooksPath /tmp/no-hooks
          npm run release -- --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: "0"  # Desabilita Husky